# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_ui', '0002_auto_20170122_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbanglog',
            name='c_order_text',
            field=models.TextField(default='-', verbose_name='Nomer PO'),
        ),
        migrations.AddField(
            model_name='timbanglog',
            name='c_orderline_text',
            field=models.TextField(default='-', verbose_name='Order Line'),
        ),
    ]
