# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_ui', '0003_auto_20170123_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbanglog',
            name='c_orderline_uom_text',
            field=models.TextField(default='-', verbose_name='UOM Orderline'),
        ),
        migrations.AddField(
            model_name='timbanglog',
            name='c_uom_text',
            field=models.TextField(default='-', verbose_name='UOM'),
        ),
        migrations.AlterField(
            model_name='timbanglog',
            name='c_orderline_id',
            field=models.IntegerField(verbose_name='Orderline'),
        ),
        migrations.AlterField(
            model_name='timbanglog',
            name='c_orderline_text',
            field=models.TextField(default='-', verbose_name='Orderline'),
        ),
    ]
