# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(unique=True, verbose_name='Date Taken')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
        ),
    ]
