# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_api', '0002_scaleconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaleconfig',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name'),
        ),
    ]
