# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scale_api', '0003_auto_20161107_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScaleLog',
        ),
        migrations.AddField(
            model_name='scaleconfig',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scaleconfig',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
