# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale_api', '0008_auto_20161123_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scaleconfig',
            options={'verbose_name': 'Scale Config'},
        ),
    ]
