# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_api', '0012_auto_20161206_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimbangLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nopol', models.CharField(max_length=40, verbose_name='Nomor Polisi')),
                ('spj', models.CharField(max_length=40, verbose_name='Nomor SPJ')),
                ('c_order', models.CharField(max_length=40, verbose_name='Nomor PO')),
                ('c_orderline', models.CharField(max_length=40, verbose_name='Produk')),
                ('c_orderline_qty', models.FloatField(verbose_name='Qty PO')),
                ('date_in', models.DateTimeField(verbose_name='Tanggal Masuk')),
                ('date_out', models.DateTimeField(null=True, verbose_name='Tanggal Keluar')),
                ('weight_in', models.FloatField(verbose_name='Berat Masuk')),
                ('weight_out', models.FloatField(null=True, verbose_name='Berat Keluar')),
                ('kadar', models.FloatField(null=True, verbose_name='Kadar Air')),
                ('kadar_max', models.FloatField(null=True, verbose_name='Kadar Air Max')),
                ('docstatus', models.CharField(choices=[('DR', 'Draft'), ('IN', 'Intransit'), ('CO', 'Complete'), ('UP', 'Uploaded')], default='IN', max_length=2, verbose_name='Doc Status')),
            ],
            options={
                'verbose_name': 'Timbang Log',
            },
        ),
    ]
