# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_api', '0013_timbanglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaleconfig',
            name='m_warehouse_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Warehouse'),
        ),
    ]
